version: '2'

services:

  app:
    build: .
    image: localhost:5000/go-demo

  unit:
    image: localhost:5000/golang:1.6
    volumes:
      - .:/usr/src/myapp
      - /tmp/go:/go
    working_dir: /usr/src/myapp
    command: bash -c "go get -d -v -t && go test --cover -v ./... && go build -v -o go-demo"

  staging-dep:
    image: localhost:5000/go-demo
    ports:
      - 8080:8080
    depends_on:
      - db

  staging:
    extends:
      service: unit
    environment:
      - HOST_IP=staging-dep:8080
    command: bash -c "go get -d -v -t && go test --tags integration -v"

  production:
    extends:
      service: unit
    environment:
      - HOST_IP=${HOST_IP}
    network_mode: host
    command: bash -c "go get -d -v -t && go test -v --tags production"

  production-loop:
    extends:
      service: production
    environment:
      - DURATION=1

  db:
    image: localhost:5000/mongo:3.2.10
