version: "3"

services:

  main:
    image: localhost:5000/go-demo${TAG}
    environment:
      - DB=db
    networks:
      - proxy
      - default
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.servicePath=${SERVICE_PATH:-/demo}
        - com.df.port=8080

  db:
    image: localhost:5000/mongo:3.2.10
    networks:
      - default

networks:
  default:
    external: false
  proxy:
    external: true
